# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Clé stockée dans le fichier .env.local
    solar_system_api_key: '%env(SOLAR_SYSTEM_API_KEY)%'
    solar_system_api_url: '%env(SOLAR_SYSTEM_API_URL)%'

    nasa_api_key: '%env(NASA_API_KEY)%'
    nasa_api_url: '%env(NASA_API_URL)%'

    iss_api_url: '%env(ISS_API_URl)%'

    people_in_space_api_url: '%env(PEOPLE_IN_SPACE_URl)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Service\PlanetService:
        arguments:
            # variables qui vont stocker notre clé via le paramètre
            $solarSystemApiKey: '%solar_system_api_key%'
            $solarSystemApiUrl: '%solar_system_api_url%'

    App\Service\SolarSystemApiService:
        arguments:
            # variables qui vont stocker notre clé via le paramètre
            $solarSystemApiKey: '%solar_system_api_key%'
            $solarSystemApiUrl: '%solar_system_api_url%'

    App\Service\ApodService:
        arguments:
            # variables qui vont stocker notre clé via le paramètre
            $nasaApiKey: '%nasa_api_key%'
            $nasaApiUrl: '%nasa_api_url%'

    App\Service\IssService:
        arguments:
            # variables qui vont stocker notre clé via le paramètre
            $issApiUrl: '%iss_api_url%'

    App\Service\PeopleInSpaceService:
        arguments:
            # variables qui vont stocker notre clé via le paramètre
            $peopleInSpaceApiUrl: '%people_in_space_api_url%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
